{{- if .Values.postmortemAgent.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "observability-agent.fullname" . }}-postmortem-agent
  labels:
    {{- include "observability-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: postmortem-agent
spec:
  replicas: {{ .Values.postmortemAgent.replicas }}
  selector:
    matchLabels:
      {{- include "observability-agent.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postmortem-agent
  template:
    metadata:
      labels:
        {{- include "observability-agent.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postmortem-agent
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: postmortem-agent
          image: "{{ .Values.global.imageRegistry }}{{ .Values.postmortemAgent.image.repository }}:{{ .Values.postmortemAgent.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy | default "IfNotPresent" }}
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "observability-agent.fullname" . }}-openai
                  key: api_key
            - name: OPENAI_MODEL
              value: {{ .Values.openai.model | default "gpt-4" | quote }}
            - name: TEMPLATE_DIR
              value: {{ .Values.knowledgeBase.postmortemTemplateDir | default "/app/templates" | quote }}
            - name: NATS_URL
              value: nats://{{ include "observability-agent.fullname" . }}-nats:4222
            {{- range .Values.agents.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- range .Values.postmortemAgent.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.postmortemAgent.resources | nindent 12 }}
{{- end }}