apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "observability-agent.fullname" . }}-runbook-agent
  labels:
    {{- include "observability-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: runbook-agent
spec:
  replicas: {{ .Values.runbookAgent.replicas }}
  selector:
    matchLabels:
      {{- include "observability-agent.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: runbook-agent
  template:
    metadata:
      labels:
        {{- include "observability-agent.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: runbook-agent
    spec:
      serviceAccountName: {{ include "observability-agent.fullname" . }}-runbook-agent
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: runbook-agent
          image: "{{ .Values.global.imageRegistry }}{{ .Values.runbookAgent.image.repository }}:{{ .Values.runbookAgent.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy | default "IfNotPresent" }}
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "observability-agent.fullname" . }}-openai
                  key: api_key
            - name: OPENAI_MODEL
              value: {{ .Values.openai.model | default "gpt-4" | quote }}
            - name: RUNBOOK_DIR
              value: {{ .Values.knowledgeBase.runbookDir | default "/app/runbooks" | quote }}
            - name: QDRANT_URL
              value: {{ .Values.knowledgeBase.qdrant.url | default (printf "http://%s-qdrant:6333" (include "observability-agent.fullname" .)) | quote }}
            - name: NATS_URL
              value: nats://{{ include "observability-agent.fullname" . }}-nats:4222
            {{- range .Values.agents.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- range .Values.runbookAgent.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.runbookAgent.resources | nindent 12 }}