apiVersion: v1
kind: Service
metadata:
  name: {{ include "observability-agent.fullname" . }}-ui-backend
  labels:
    {{- include "observability-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui-backend
spec:
  type: {{ .Values.uiBackend.service.type }}
  ports:
    - port: {{ .Values.uiBackend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "observability-agent.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui-backend
